name: pyvista-environment
channels:
  - pyviz
dependencies:
  - python=3.7
  - bokeh
  - pyviz_comms
  - panel
  - lxml
  - pyvirtualdisplay
  - pip:
    - git+git://github.com/tkoyama010/pyvista@patch-3
    - matplotlib
    - pyct
